import { useState, useEffect } from 'react';
import { Download, Plus, X, FileText, Eye, Search } from 'lucide-react';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { mockReportsInit } from '../mocks/data';

type Report = {
  id: string; name: string; type: string; date: string;
  status: 'Ready' | 'Generating'; format: string; actor: string;
  progress?: number;
};

const REPORT_TYPES = ['Actor Profile', 'Summary', 'Tech Report', 'Custom'];
const ACTORS = ['DarkVendorX', 'AlphaBay_Seller', 'SilentCrow', 'EvilCore', 'All', 'Multiple'];
const FORMATS = ['PDF', 'JSON', 'CSV'];

const generateContent = (r: Report) => `
THREATLENS INTELLIGENCE REPORT
================================
Report Name : ${r.name}
Type        : ${r.type}
Actor       : ${r.actor}
Format      : ${r.format}
Generated   : ${new Date().toISOString()}
Status      : ${r.status}

EXECUTIVE SUMMARY
-----------------
This report was automatically generated by the ThreatLens Intelligence Platform.

All data in this report is derived from authorized intelligence sources and is
annotated with evidence grades (High / Moderate / Low / Weak).

FINDINGS
--------
• Actor: ${r.actor}
• Primary Category: Initial Access Broker / Marketplace Vendor
• Confidence Level: High (88%)
• Last Observed: 2026-09-25
• Linked Identifiers: 4 (PGP Key, BTC Wallet, Tor Domain, Email)
• Known Relationships: 7 edges
• Infrastructure Indicators: 3 onion services

EVIDENCE SUMMARY
----------------
EV-8921 | SSL Certificate Reuse | SHA-256: 8f4e2... | Confidence: High
EV-9014 | Server Status Exposed | Apache mod_status leak | Confidence: Moderate
EV-4412 | Forum Post Text       | Comma splice pattern  | Confidence: High
EV-3021 | PGP Public Key Block  | 0xA3F9D2C            | Confidence: Confirmed

ATTRIBUTION NOTE
----------------
This report presents investigative leads and evidence-based relationships.
It does not constitute proof of real-world identity. All findings are
subject to analyst review and independent verification.

[END OF REPORT]
`.trim();

const ReportPreviewModal = ({ report, onClose }: { report: Report; onClose: () => void }) => (
  <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-50 p-4">
    <div className="bg-card border border-border-subtle rounded-xl w-full max-w-2xl shadow-2xl max-h-[85vh] flex flex-col">
      <div className="flex items-center justify-between p-5 border-b border-border-subtle">
        <div className="flex items-center gap-3">
          <FileText className="w-5 h-5 text-accent-solid" />
          <h2 className="font-bold text-text-primary">{report.name}</h2>
          <span className="text-xs px-2 py-0.5 bg-accent-soft/20 text-accent-link rounded-full">{report.format}</span>
        </div>
        <button onClick={onClose} className="text-text-muted hover:text-text-primary p-1 rounded hover:bg-card-hover">
          <X className="w-4 h-4" />
        </button>
      </div>
      <div className="flex-1 overflow-auto p-5">
        <pre className="text-xs text-status-green font-mono whitespace-pre-wrap bg-canvas-dark border border-border-subtle rounded-lg p-4">
          {generateContent(report)}
        </pre>
      </div>
      <div className="p-4 border-t border-border-subtle flex justify-end gap-3">
        <Button variant="secondary" onClick={onClose}>Close</Button>
        <Button onClick={() => {
          const b = new Blob([generateContent(report)], { type: 'text/plain' });
          const u = URL.createObjectURL(b);
          const a = document.createElement('a'); a.href = u;
          a.download = `${report.name.replace(/\s+/g, '_')}.${report.format.toLowerCase()}`;
          a.click();
        }}>
          <Download className="w-4 h-4 mr-2" /> Download
        </Button>
      </div>
    </div>
  </div>
);

const NewReportModal = ({ onClose, onGenerate }: { onClose: () => void; onGenerate: (r: Report) => void }) => {
  const [name, setName] = useState('');
  const [type, setType] = useState(REPORT_TYPES[0]);
  const [actor, setActor] = useState(ACTORS[0]);
  const [format, setFormat] = useState(FORMATS[0]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim()) return;
    onGenerate({
      id: `r_${Date.now()}`,
      name: name.trim(), type, actor, format,
      date: new Date().toLocaleDateString('en-GB'),
      status: 'Generating', progress: 0,
    });
    onClose();
  };

  return (
    <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-50 p-4">
      <div className="bg-card border border-border-subtle rounded-xl w-full max-w-md shadow-2xl">
        <div className="flex items-center justify-between p-5 border-b border-border-subtle">
          <h2 className="font-bold text-text-primary">Generate New Report</h2>
          <button onClick={onClose} className="text-text-muted hover:text-text-primary"><X className="w-4 h-4" /></button>
        </div>
        <form onSubmit={handleSubmit} className="p-5 space-y-4">
          <div>
            <label className="text-xs text-text-muted uppercase tracking-wider block mb-1.5">Report Name *</label>
            <input type="text" value={name} onChange={e => setName(e.target.value)} required
              placeholder="e.g., DarkVendorX Profile Report"
              className="w-full px-3 py-2.5 bg-input border border-border-subtle rounded-lg text-text-primary placeholder-text-muted focus:outline-none focus:border-accent-border text-sm" />
          </div>
          {[
            { label: 'Report Type', value: type, setter: setType, opts: REPORT_TYPES },
            { label: 'Target Actor', value: actor, setter: setActor, opts: ACTORS },
            { label: 'Export Format', value: format, setter: setFormat, opts: FORMATS },
          ].map(({ label, value, setter, opts }) => (
            <div key={label}>
              <label className="text-xs text-text-muted uppercase tracking-wider block mb-1.5">{label}</label>
              <select value={value} onChange={e => setter(e.target.value)}
                className="w-full px-3 py-2.5 bg-input border border-border-subtle rounded-lg text-text-primary focus:outline-none focus:border-accent-border text-sm">
                {opts.map(o => <option key={o}>{o}</option>)}
              </select>
            </div>
          ))}
          <div className="pt-2 flex gap-3 justify-end">
            <Button variant="secondary" type="button" onClick={onClose}>Cancel</Button>
            <Button type="submit" disabled={!name.trim()}>Generate Report</Button>
          </div>
        </form>
      </div>
    </div>
  );
};

const Reports = () => {
  const [reports, setReports] = useState<Report[]>(mockReportsInit as Report[]);
  const [showNew, setShowNew] = useState(false);
  const [preview, setPreview] = useState<Report | null>(null);
  const [search, setSearch] = useState('');

  // Simulate Generating → Ready
  useEffect(() => {
    const interval = setInterval(() => {
      setReports(prev => prev.map(r => {
        if (r.status !== 'Generating') return r;
        const prog = (r.progress ?? 0) + 25;
        if (prog >= 100) return { ...r, status: 'Ready', progress: 100 };
        return { ...r, progress: prog };
      }));
    }, 1000);
    return () => clearInterval(interval);
  }, []);

  const handleGenerate = (r: Report) => setReports(prev => [r, ...prev]);

  const handleDownload = (r: Report) => {
    const b = new Blob([generateContent(r)], { type: 'text/plain' });
    const u = URL.createObjectURL(b);
    const a = document.createElement('a'); a.href = u;
    a.download = `${r.name.replace(/\s+/g, '_')}.${r.format.toLowerCase()}`;
    a.click();
  };

  const filtered = reports.filter(r =>
    r.name.toLowerCase().includes(search.toLowerCase()) ||
    r.actor.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl text-text-primary font-bold">Reports</h1>
          <p className="text-text-secondary mt-1">Generate, preview, and export analytical intelligence reports.</p>
        </div>
        <Button onClick={() => setShowNew(true)}>
          <Plus className="w-4 h-4 mr-2" /> New Report
        </Button>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-3 gap-4">
        {[
          { label: 'Total Reports', val: reports.length },
          { label: 'Ready', val: reports.filter(r => r.status === 'Ready').length },
          { label: 'Generating', val: reports.filter(r => r.status === 'Generating').length },
        ].map(s => (
          <Card key={s.label} className="py-4 text-center">
            <div className="text-2xl font-bold text-text-primary">{s.val}</div>
            <div className="text-xs text-text-muted mt-1">{s.label}</div>
          </Card>
        ))}
      </div>

      {/* Search */}
      <div className="relative max-w-sm">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-text-muted" />
        <input type="text" value={search} onChange={e => setSearch(e.target.value)}
          placeholder="Search reports..."
          className="pl-9 pr-3 py-2 text-sm bg-input border border-border-subtle rounded-lg text-text-primary placeholder-text-muted focus:outline-none focus:border-accent-border w-full" />
      </div>

      {/* Table */}
      <Card className="p-0 overflow-hidden">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="border-b border-border-subtle bg-canvas-dark">
              {['Report Name', 'Type', 'Actor', 'Format', 'Created', 'Status', 'Actions'].map(h => (
                <th key={h} className={`py-3 px-4 text-xs font-semibold text-text-muted uppercase tracking-wider ${h === 'Actions' ? 'text-right' : ''}`}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-border-subtle">
            {filtered.map((r) => (
              <tr key={r.id} className="hover:bg-card-hover transition-colors">
                <td className="py-3 px-4">
                  <button
                    onClick={() => r.status === 'Ready' && setPreview(r)}
                    className={`text-sm font-medium text-left ${r.status === 'Ready' ? 'text-accent-link hover:underline cursor-pointer' : 'text-text-primary cursor-default'}`}
                  >
                    {r.name}
                  </button>
                </td>
                <td className="py-3 px-4 text-sm text-text-secondary">{r.type}</td>
                <td className="py-3 px-4 text-sm text-text-secondary">{r.actor}</td>
                <td className="py-3 px-4">
                  <span className="text-xs font-mono px-2 py-0.5 bg-border-subtle text-text-secondary rounded">{r.format}</span>
                </td>
                <td className="py-3 px-4 text-sm text-text-muted">{r.date}</td>
                <td className="py-3 px-4">
                  {r.status === 'Generating' ? (
                    <div className="space-y-1">
                      <span className="text-xs font-medium text-status-orange">Generating…</span>
                      <div className="h-1 w-24 bg-border-subtle rounded-full overflow-hidden">
                        <div className="h-full bg-status-orange rounded-full transition-all" style={{ width: `${r.progress ?? 0}%` }} />
                      </div>
                    </div>
                  ) : (
                    <span className="px-2 py-1 text-xs font-medium rounded-full bg-status-green/10 text-status-green">Ready</span>
                  )}
                </td>
                <td className="py-3 px-4 text-right">
                  <div className="flex items-center justify-end gap-1">
                    {r.status === 'Ready' && (
                      <Button variant="ghost" onClick={() => setPreview(r)} title="Preview">
                        <Eye className="w-4 h-4" />
                      </Button>
                    )}
                    <Button variant="ghost" disabled={r.status === 'Generating'} onClick={() => handleDownload(r)} title="Download">
                      <Download className="w-4 h-4" />
                    </Button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        {filtered.length === 0 && (
          <div className="text-center py-12 text-text-muted">No reports match your search.</div>
        )}
      </Card>

      {showNew && <NewReportModal onClose={() => setShowNew(false)} onGenerate={handleGenerate} />}
      {preview && <ReportPreviewModal report={preview} onClose={() => setPreview(null)} />}
    </div>
  );
};

export default Reports;
