import React, { useState, useEffect } from 'react';
import { Download, Plus, X, FileText, Eye, Search } from 'lucide-react';
import { Button } from '../components/ui/Button';
import { mockReportsInit } from '../mocks/data';

type Report = {
  id: string; name: string; type: string; date: string;
  status: 'Ready' | 'Generating'; format: string; actor: string;
  progress?: number;
};

const REPORT_TYPES = ['Actor Profile', 'Summary', 'Tech Report', 'Custom'];
const ACTORS = ['DarkVendorX', 'AlphaBay_Seller', 'SilentCrow', 'EvilCore', 'All', 'Multiple'];
const FORMATS = ['PDF', 'JSON', 'CSV'];

const generateContent = (r: Report) => `
THREATLENS INTELLIGENCE REPORT
================================
Report Name : ${r.name}
Type        : ${r.type}
Actor       : ${r.actor}
Format      : ${r.format}
Generated   : ${new Date().toISOString()}
Status      : ${r.status}

EXECUTIVE SUMMARY
-----------------
This report was automatically generated by the ThreatLens Intelligence Platform.
All data in this report is derived from authorized intelligence sources and is
annotated with evidence grades (High / Moderate / Low / Weak).

FINDINGS
--------
• Actor: ${r.actor}
• Primary Category: Initial Access Broker / Marketplace Vendor
• Confidence Level: High (88%)
• Last Observed: 2026-09-25
• Linked Identifiers: 4 (PGP Key, BTC Wallet, Tor Domain, Email)
• Known Relationships: 7 edges
• Infrastructure Indicators: 3 onion services

EVIDENCE SUMMARY
----------------
EV-8921 | SSL Certificate Reuse | SHA-256: 8f4e2... | Confidence: High
EV-9014 | Server Status Exposed | Apache mod_status leak | Confidence: Moderate
EV-4412 | Forum Post Text       | Comma splice pattern  | Confidence: High
EV-3021 | PGP Public Key Block  | 0xA3F9D2C            | Confidence: Confirmed

ATTRIBUTION NOTE
----------------
This report presents investigative leads and evidence-based relationships.
It does not constitute proof of real-world identity. All findings are
subject to analyst review and independent verification.

[END OF REPORT]
`.trim();

const ReportPreviewModal = ({ report, onClose }: { report: Report; onClose: () => void }) => (
  <div className="fixed inset-0 bg-canvas/80 backdrop-blur-md flex items-center justify-center z-50 p-4 font-mono">
    <div className="bg-surface border border-border-subtle rounded-[6px] w-full max-w-2xl shadow-2xl max-h-[85vh] flex flex-col">
      <div className="flex items-center justify-between p-5 border-b border-border-subtle">
        <div className="flex items-center gap-3">
          <FileText className="w-4 h-4 text-accent-solid" strokeWidth={1.5} />
          <h2 className="font-semibold text-text-primary text-xs uppercase">{report.name}</h2>
          <span className="text-[10px] px-2 py-0.5 bg-accent-soft text-accent-solid border border-accent-border/40 uppercase">{report.format}</span>
        </div>
        <button onClick={onClose} className="text-text-muted hover:text-text-primary text-xs">✕</button>
      </div>
      <div className="flex-1 overflow-auto p-5">
        <pre className="text-xs text-accent-solid font-mono whitespace-pre-wrap bg-canvas-deep border border-border-subtle rounded-[4px] p-4">
          {generateContent(report)}
        </pre>
      </div>
      <div className="p-4 border-t border-border-subtle flex justify-end gap-3">
        <Button variant="secondary" onClick={onClose} className="text-xs uppercase font-mono">Close</Button>
        <Button onClick={() => {
          const b = new Blob([generateContent(report)], { type: 'text/plain' });
          const u = URL.createObjectURL(b);
          const a = document.createElement('a'); a.href = u;
          a.download = `${report.name.replace(/\s+/g, '_')}.${report.format.toLowerCase()}`;
          a.click();
        }} className="text-xs uppercase font-mono">
          <Download className="w-3.5 h-3.5 mr-1.5" strokeWidth={1.5} /> Download
        </Button>
      </div>
    </div>
  </div>
);

const NewReportModal = ({ onClose, onGenerate }: { onClose: () => void; onGenerate: (r: Report) => void }) => {
  const [name, setName] = useState('');
  const [type, setType] = useState(REPORT_TYPES[0]);
  const [actor, setActor] = useState(ACTORS[0]);
  const [format, setFormat] = useState(FORMATS[0]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim()) return;
    onGenerate({
      id: `r_${Date.now()}`,
      name: name.trim(), type, actor, format,
      date: new Date().toLocaleDateString('en-GB'),
      status: 'Generating', progress: 0,
    });
    onClose();
  };

  return (
    <div className="fixed inset-0 bg-canvas/80 backdrop-blur-md flex items-center justify-center z-50 p-4 font-mono">
      <div className="bg-surface border border-border-subtle rounded-[6px] w-full max-w-md shadow-2xl">
        <div className="flex items-center justify-between p-5 border-b border-border-subtle">
          <h2 className="font-semibold text-text-primary text-xs uppercase tracking-wider">// GENERATE NEW REPORT</h2>
          <button onClick={onClose} className="text-text-muted hover:text-text-primary text-xs">✕</button>
        </div>
        <form onSubmit={handleSubmit} className="p-5 space-y-4 text-xs">
          <div>
            <label className="text-[10px] text-text-muted uppercase tracking-wider block mb-1.5">Report Name *</label>
            <input type="text" value={name} onChange={e => setName(e.target.value)} required
              placeholder="e.g., DarkVendorX Profile Report"
              className="w-full px-3 py-2 bg-canvas-deep border border-border-subtle rounded-[4px] text-text-primary font-mono focus:outline-none focus:border-accent-border text-xs" />
          </div>
          {[
            { label: 'Report Type', value: type, setter: setType, opts: REPORT_TYPES },
            { label: 'Target Actor', value: actor, setter: setActor, opts: ACTORS },
            { label: 'Export Format', value: format, setter: setFormat, opts: FORMATS },
          ].map(({ label, value, setter, opts }) => (
            <div key={label}>
              <label className="text-[10px] text-text-muted uppercase tracking-wider block mb-1.5">{label}</label>
              <select value={value} onChange={e => setter(e.target.value)}
                className="w-full px-3 py-2 bg-canvas-deep border border-border-subtle rounded-[4px] text-text-primary font-mono focus:outline-none focus:border-accent-border text-xs">
                {opts.map(o => <option key={o}>{o}</option>)}
              </select>
            </div>
          ))}
          <div className="pt-2 flex gap-3 justify-end">
            <Button variant="secondary" type="button" onClick={onClose} className="text-xs uppercase font-mono">Cancel</Button>
            <Button type="submit" disabled={!name.trim()} className="text-xs uppercase font-mono">Generate Report</Button>
          </div>
        </form>
      </div>
    </div>
  );
};

const Reports = () => {
  const [reports, setReports] = useState<Report[]>(mockReportsInit as Report[]);
  const [showNew, setShowNew] = useState(false);
  const [preview, setPreview] = useState<Report | null>(null);
  const [search, setSearch] = useState('');

  // Simulate Generating → Ready
  useEffect(() => {
    const interval = setInterval(() => {
      setReports(prev => prev.map(r => {
        if (r.status !== 'Generating') return r;
        const prog = (r.progress ?? 0) + 25;
        if (prog >= 100) return { ...r, status: 'Ready', progress: 100 };
        return { ...r, progress: prog };
      }));
    }, 1000);
    return () => clearInterval(interval);
  }, []);

  const handleGenerate = (r: Report) => setReports(prev => [r, ...prev]);

  const handleDownload = (r: Report) => {
    const b = new Blob([generateContent(r)], { type: 'text/plain' });
    const u = URL.createObjectURL(b);
    const a = document.createElement('a'); a.href = u;
    a.download = `${r.name.replace(/\s+/g, '_')}.${r.format.toLowerCase()}`;
    a.click();
  };

  const filtered = reports.filter(r =>
    r.name.toLowerCase().includes(search.toLowerCase()) ||
    r.actor.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="space-y-8 animate-fade-in font-sans selection:bg-accent-soft selection:text-accent-solid">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-border-subtle pb-4">
        <div>
          <p className="text-[10px] font-mono tracking-[0.25em] text-accent-solid uppercase mb-1">// 08 REPORTS & EXPORTS</p>
          <h1 className="text-xl font-mono font-bold text-text-primary uppercase tracking-wide">
            INTELLIGENCE REPORTS & EXPORTS
          </h1>
        </div>
        <Button onClick={() => setShowNew(true)} className="h-9 font-mono text-xs uppercase tracking-wider">
          <Plus className="w-3.5 h-3.5 mr-1.5" strokeWidth={1.5} /> New Report
        </Button>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 font-mono">
        {[
          { label: 'TOTAL REPORTS', val: reports.length, color: 'text-accent-solid' },
          { label: 'READY FOR EXPORT', val: reports.filter(r => r.status === 'Ready').length, color: 'text-status-green' },
          { label: 'GENERATING IN BACKGROUND', val: reports.filter(r => r.status === 'Generating').length, color: 'text-status-orange' },
        ].map(s => (
          <div key={s.label} className="bg-surface border border-border-subtle p-5 rounded-[6px]">
            <div className="text-[9px] text-text-muted uppercase tracking-widest">{s.label}</div>
            <div className={`mt-2 text-2xl font-bold ${s.color} tabular-nums`}>{s.val}</div>
          </div>
        ))}
      </div>

      {/* Search Bar */}
      <div className="relative max-w-sm font-mono">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-text-muted pointer-events-none" strokeWidth={1.5} />
        <input
          type="search"
          value={search}
          onChange={e => setSearch(e.target.value)}
          placeholder="Search reports..."
          className="w-full pl-9 pr-3 py-2 bg-canvas-deep border border-border-subtle rounded-[4px] text-xs font-mono text-text-primary placeholder:text-text-muted/60 focus:outline-none focus:border-accent-border"
        />
      </div>

      {/* Table */}
      <div className="bg-surface border border-border-subtle rounded-[6px] overflow-hidden font-mono text-xs">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b border-border-subtle text-[10px] text-text-muted uppercase tracking-widest bg-canvas-deep">
                <th className="py-3 px-5">Report Name</th>
                <th className="py-3 px-5">Type</th>
                <th className="py-3 px-5">Actor</th>
                <th className="py-3 px-5">Format</th>
                <th className="py-3 px-5">Created</th>
                <th className="py-3 px-5">Status</th>
                <th className="py-3 px-5 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border-subtle/50">
              {filtered.map((r) => (
                <tr key={r.id} className="hover:bg-card-hover/40 transition-colors">
                  <td className="py-3.5 px-5">
                    <button
                      onClick={() => r.status === 'Ready' && setPreview(r)}
                      className={`text-xs font-mono font-semibold text-left ${r.status === 'Ready' ? 'text-accent-solid hover:underline cursor-pointer' : 'text-text-primary cursor-default'}`}
                    >
                      {r.name}
                    </button>
                  </td>
                  <td className="py-3.5 px-5 text-text-secondary">{r.type}</td>
                  <td className="py-3.5 px-5 text-text-secondary">{r.actor}</td>
                  <td className="py-3.5 px-5">
                    <span className="text-[9px] font-mono px-2 py-0.5 bg-canvas-deep border border-border-subtle text-text-secondary rounded-[3px] uppercase">{r.format}</span>
                  </td>
                  <td className="py-3.5 px-5 text-text-muted">{r.date}</td>
                  <td className="py-3.5 px-5">
                    {r.status === 'Generating' ? (
                      <div className="space-y-1">
                        <span className="text-[10px] font-mono text-status-orange uppercase">Generating… ({r.progress}%)</span>
                        <div className="h-px w-24 bg-border-subtle overflow-hidden">
                          <div className="h-px bg-status-orange transition-all" style={{ width: `${r.progress ?? 0}%` }} />
                        </div>
                      </div>
                    ) : (
                      <span className="px-2 py-0.5 text-[9px] font-mono rounded-[3px] bg-status-green-bg text-status-green border border-status-green/30 uppercase">Ready</span>
                    )}
                  </td>
                  <td className="py-3.5 px-5 text-right">
                    <div className="flex items-center justify-end gap-1">
                      {r.status === 'Ready' && (
                        <Button variant="ghost" onClick={() => setPreview(r)} title="Preview" className="p-1.5 text-text-muted hover:text-text-primary">
                          <Eye className="w-3.5 h-3.5" strokeWidth={1.5} />
                        </Button>
                      )}
                      <Button variant="ghost" disabled={r.status === 'Generating'} onClick={() => handleDownload(r)} title="Download" className="p-1.5 text-text-muted hover:text-text-primary">
                        <Download className="w-3.5 h-3.5" strokeWidth={1.5} />
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {showNew && <NewReportModal onClose={() => setShowNew(false)} onGenerate={handleGenerate} />}
      {preview && <ReportPreviewModal report={preview} onClose={() => setPreview(null)} />}
    </div>
  );
};

export default Reports;
